// index.js
// 获取应用实例
Page({
  data: {
    //商品数据
    goods:[
      {
        goods_name:"800g九十九度",
        goods_price:100,
        goods_num:0,
        isActive:true
      },
      {
        goods_name:"800g笨小鸭",
        goods_price:1,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"1kg笨小鸭",
        goods_price:2,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"1.2kg笨小鸭",
        goods_price:3,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"红羽毛",
        goods_price:0,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"脸谱",
        goods_price:0,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"1250g笨小鸭",
        goods_price:0,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"1300g笨小鸭",
        goods_price:0,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"1700g笨小鸭",
        goods_price:0,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"4斤",
        goods_price:0,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"4.5斤",
        goods_price:0,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"5斤",
        goods_price:0,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"24卷",
        goods_price:0,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"7.5斤",
        goods_price:0,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"8斤",
        goods_price:0,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"9斤",
        goods_price:0,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"喜福",
        goods_price:0,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"10斤",
        goods_price:0,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"10斤笨",
        goods_price:0,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"6包抽",
        goods_price:0,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"10包抽",
        goods_price:0,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"5毛手巾纸",
        goods_price:0,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"1元手帕纸",
        goods_price:0,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"10片湿巾",
        goods_price:0,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"80片湿巾",
        goods_price:0,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"奇强洗洁精",
        goods_price:0,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"大精",
        goods_price:0,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"袋洗1kg",
        goods_price:0,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"240g粉",
        goods_price:0,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"455g粉",
        goods_price:0,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"1018g粉",
        goods_price:0,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"202g皂",
        goods_price:0,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"218g晶彩皂",
        goods_price:0,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"生产队扑克",
        goods_price:0,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"正点纸盒",
        goods_price:0,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"正点塑盒",
        goods_price:0,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"散精",
        goods_price:0,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"505",
        goods_price:0,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"一口净",
        goods_price:0,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"131B",
        goods_price:0,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"761",
        goods_price:0,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"105B",
        goods_price:0,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"3元无烟",
        goods_price:0,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"4元无香",
        goods_price:0,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"5元儿香",
        goods_price:0,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"600ml正点香型",
        goods_price:0,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"600ml正点无味",
        goods_price:0,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"600ml正点儿童",
        goods_price:0,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"750ml正点无味",
        goods_price:0,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"正点器+液",
        goods_price:0,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"正点器+片",
        goods_price:0,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"正点片",
        goods_price:0,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"正点液",
        goods_price:0,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"赖无味",
        goods_price:0,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"童画香型",
        goods_price:0,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"童画无味",
        goods_price:0,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"童画儿童",
        goods_price:0,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"童画片",
        goods_price:0,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"童画液",
        goods_price:0,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"童画器+片",
        goods_price:0,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"童画器+液",
        goods_price:0,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"童画蝇香",
        goods_price:0,
        goods_num:0,
        isActive:false
      },
      {
        goods_name:"童画加长蝇香",
        goods_price:0,
        goods_num:0,
        isActive:false
      }

    ],
    //商品总价格
    goods_all_price:0
  },
  onShow(){

  },
  //数量加减
  handleItemNumEdit(e){
    const goods = this.data.goods;
    const index = goods.findIndex(v=>v.goods_name===e.currentTarget.dataset.goods_name);
    if(goods[index].goods_num===0&&e.currentTarget.dataset.operation===-1){
      wx.showToast({
        title: '不能再减少了',
        icon: 'none',
        mask: true,
      });
    }else{
      goods[index].goods_num += e.currentTarget.dataset.operation;
      var goods_all_price = 0;
      goods.forEach(function(item, index){
        goods_all_price += item.goods_num*item.goods_price;
      });
      this.setData({goods,goods_all_price})
    }
    
  }
})
